// Generated by LiveScript 1.3.1
(function(){
  define(['ng', 'ink', 'ink-ui'], function(){
    var mkTemplate, basicFactory;
    mkTemplate = function(mode){
      var beginning, ending;
      beginning = '<div class="hide-all ink-alert basic ';
      ending = '"><button class="ink-dismiss" ng-click="hidalerts()" >&times;</button><div ng-transclude></div></div>';
      if (mode) {
        return beginning.concat(mode, ending);
      } else {
        return beginning.concat(ending);
      }
    };
    basicFactory = {
      replace: true,
      transclude: true,
      restrict: 'A',
      controller: function($scope, $element, $attrs, $transclude){
        return $scope.hidalerts = function(){
          return angular.element('.ink-alert').removeClass('show-all').addClass('hide-all');
        };
      }
    };
    return angular.module('alert', []).directive('alert', function(){
      var out;
      out = {
        template: mkTemplate()
      };
      return import$(out, basicFactory);
    }).directive('info', function(){
      var out;
      out = {
        template: mkTemplate('info')
      };
      return import$(out, basicFactory);
    }).directive('error', function(){
      var out;
      out = {
        template: mkTemplate('error')
      };
      return import$(out, basicFactory);
    }).directive('success', function(){
      var out;
      out = {
        template: mkTemplate('success')
      };
      return import$(out, basicFactory);
    });
  });
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
