// Generated by LiveScript 1.3.1
/* Small module that replaces hr with div.hr, used for presentation finesse */
(function(){
  define(['ng'], function(){
    return angular.module('hr', []).directive('hr', function(){
      return {
        link: function(scope, elt, attrs){
          return elt.replaceWith("<div class='hr'>*&nbsp;&nbsp;&nbsp;*&nbsp;&nbsp;&nbsp;*</div>");
        },
        restrict: 'E'
      };
    });
  });
}).call(this);
