// Generated by LiveScript 1.3.1
/* Small module that wraps all .logo elts in a link to the root */
(function(){
  define(['ng'], function(){
    return angular.module('logo', []).directive('logo', function(){
      return {
        link: function(scope, elt, attrs){
          return elt.replaceWith("<a class='logo' href='/'>".concat(elt.text(), "</a>"));
        },
        restrict: 'C'
      };
    });
  });
}).call(this);
