// Generated by LiveScript 1.3.1
(function(){
  var siteController;
  siteController = function($scope){
    return console.log("Site initialized");
  };
  define(['ng'], function(){
    return angular.module('site', ['logo', 'hr']).controller('Site', ['$scope', siteController]);
  });
}).call(this);
